// Copyright 2026 Chuvadi Contributors
// SPDX-License-Identifier: Apache-2.0
// PHASE: M2a — golden fixtures generated by tools/gen_zint_fixtures.py (Zint 2.13.0, test oracle only)

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Xunit;

namespace Chuvadi.Barcodes.Encoders.Tests;

internal sealed class ZintFixture
{
    private ZintFixture(string name, Dictionary<string, string> meta, BitMatrix matrix)
    {
        Name = name;
        Meta = meta;
        Matrix = matrix;
    }

    public string Name { get; }

    public Dictionary<string, string> Meta { get; }

    public BitMatrix Matrix { get; }

    public string Input => Utf8FromHex(Meta.TryGetValue("input-hex", out string? hex) ? hex : Meta["data-hex"]);

    public QrErrorCorrectionLevel Ecc => Enum.Parse<QrErrorCorrectionLevel>(Meta["ecc"]);

    public int? Version => Meta.TryGetValue("version", out string? v) ? int.Parse(v, System.Globalization.CultureInfo.InvariantCulture) : null;

    public int? Mask => Meta["mask"] == "auto" ? null : int.Parse(Meta["mask"], System.Globalization.CultureInfo.InvariantCulture);

    public QrCharacterSet CharacterSet => Enum.Parse<QrCharacterSet>(Meta["charset"]);

    public bool Gs1 => Meta.TryGetValue("gs1", out string? g) && g == "1";

    public int StructuredAppendIndex => int.Parse(Meta["sa-index"], System.Globalization.CultureInfo.InvariantCulture);

    public int StructuredAppendCount => Meta.TryGetValue("sa-count", out string? c) ? int.Parse(c, System.Globalization.CultureInfo.InvariantCulture) : 0;

    public string StructuredAppendFullText => Utf8FromHex(Meta["sa-full-hex"]);

    public static string Directory(string symbology) =>
        Path.Combine(AppContext.BaseDirectory, "Fixtures", "Zint", symbology);

    public static TheoryData<string> Names(string symbology)
    {
        TheoryData<string> data = [];
        foreach (string file in System.IO.Directory.GetFiles(Directory(symbology), "*.txt").Order(StringComparer.Ordinal))
        {
            data.Add(Path.GetFileNameWithoutExtension(file));
        }

        return data;
    }

    public static ZintFixture Load(string symbology, string name)
    {
        string[] lines = File.ReadAllLines(Path.Combine(Directory(symbology), name + ".txt"));
        Dictionary<string, string> meta = new(StringComparer.Ordinal);
        int i = 0;
        for (; i < lines.Length; i++)
        {
            string line = lines[i];
            if (line.StartsWith('#'))
            {
                continue;
            }

            if (line == "matrix:")
            {
                i++;
                break;
            }

            int colon = line.IndexOf(':', StringComparison.Ordinal);
            meta[line[..colon]] = line[(colon + 1)..].Trim();
        }

        BitMatrix matrix = BitMatrix.Parse(string.Join('\n', lines.Skip(i)));
        return new ZintFixture(name, meta, matrix);
    }

    private static string Utf8FromHex(string hex) => Encoding.UTF8.GetString(Convert.FromHexString(hex));
}
